### ISSUE TITLE
changelog?

### ISSUE THREAD

**Issue by r-lyeh** [monolifed/tiny-regex-mod#1]
Could you enumerate the changes you made whether in README and/or source code?
Thx!

**Comment by monolifed** [comment]
Unfortunately I didn't really keep a log of changes. But as far as I can remember:
- made it into a single file library
- modified to return a pointer to the start of the match (instead of an integer)
- added option to get a pointer to the end of the match
- removed static use of regex object
- added quantifier operator `{m,n}` (also `{m}`, `{m,}`)
- added lazy quantifiers `??`, `*?`, `+?` and `{m,n}?`
- merged quantifier (?,*,+,{}) matching into two function (one for greedy, one for lazy)
- added upper limits to quantifiers
- (hopefully) fixed class range matching
- (hopefully) fixed handling of escape characters
- (hopefully) fixed `.` matching (doesn't match `\r` or `\n`)
- probably butchered print functionality

**Comment by r-lyeh** [comment]
Good additions! Thank you :D

PS: Suggestion: rewrite git commit/history so each feature is committed separately. Not big deal but nice anyways :D
